language: node_js
node_js:
  - "10"
  - "12"
cache:
  directories:
    - "node_modules"
before_script:
  - npm run build
script:
  - npm run test:cov
  - npm run lint:all
before_deploy:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip python3-setuptools
  - pip3 install --user catapultdocscli
  - npm link
  - CURRENT_VERSION=$(npm run version --silent)
  - catapult-docs-cli cli-usage --config .clidocs > docs/$CURRENT_VERSION.md
deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/github-pages.sh
    on:
      branch: master
      node_js: "10"
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/uploadArchives.sh
    on:
      branch: master
      node_js: "10"
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/release.sh
    on:
      branch: $RELEASE_BRANCH
      node_js: "10"
